---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vm3xrrup9tqw/public_html/inventory
    - /bin/cp -Rf api/. $DEPLOYPATH/api/
    - /bin/cp -Rf dist/. $DEPLOYPATH/
    - /bin/cp -f /home/vm3xrrup9tqw/secure_backups/inventory-config.php $DEPLOYPATH/api/config/config.php
